version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - err113
    - exhaustruct
    - gocognit
    - ireturn
    - maintidx
    - nestif
    - nlreturn
    - noctx
    - paralleltest
    - tagliatelle
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 220
      statements: 120
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 64
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
