linters-settings:
  gocyclo:
    min-complexity: 64
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  # TODO: Revisit after the refactor
  funlen:
    lines: 220
    statements: 120

linters:
  enable-all: true
  disable:
    - depguard
    - ireturn
    - maintidx
    - wrapcheck
    - nlreturn
    - noctx
    - paralleltest
    - exhaustruct
    - tagliatelle
    - err113
    - dupl
    - wsl
    # TODO: Revisit after the refactor
    - gocognit
    - nestif