name: Build & Lint

# Only trigger the event on pull-requests
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Test the latest release of Go
    strategy:
      matrix:
        go: ["1.24"]
    steps:
      # Setup the workflow to use the specific version of Go
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Verify downloaded dependencies
      - name: Verify dependencies
        run: go mod verify
      - name: "Create k3d Cluster for E2E testing"
        uses: AbsaOSS/k3d-action@v2.4.0
        with:
          cluster-name: "testcluster"
          args: >-
            -p "8443:443@loadbalancer"
      - name: "Deploy keycloak"
        run: |
          k3d kubeconfig merge testcluster --kubeconfig-switch-context
          export KUBECONFIG=~/.k3d/kubeconfig-testcluster.yaml
          kubectl apply -f ./e2e/k8s/manifest.yml
      - name: "Deploy Redis"
        run: |
          sudo apt install -y redis

          REDIS_DIR=/tmp/redis-standalone
          mkdir -p $REDIS_DIR
          cp e2e/redis/redis.conf ${REDIS_DIR}/redis.conf
          cp e2e/redis/{ca.crt,redis.crt,redis.key} $REDIS_DIR
          pushd $REDIS_DIR
          redis-server ./redis.conf &
          popd
      - name: "Setup Redis Cluster"
        run: |
          sudo apt install -y redis
          PORT_PREFIX=700
          for NODE_NUM in {0..5}
          do
              REDIS_DIR=/tmp/redis-$NODE_NUM
              mkdir -p $REDIS_DIR
              cp e2e/redis/redis-cluster.conf ${REDIS_DIR}/redis.conf
              echo "tls-port ${PORT_PREFIX}${NODE_NUM}" >> ${REDIS_DIR}/redis.conf
              cp e2e/redis/{ca.crt,redis.crt,redis.key} $REDIS_DIR
              pushd $REDIS_DIR
              redis-server ./redis.conf &
              popd
          done

          sleep 3

          redis-cli --cluster create 127.0.0.1:${PORT_PREFIX}{0..5} \
              --cluster-replicas 1 \
              --cluster-yes \
              --tls \
              --cacert e2e/redis/ca.crt \
              --key e2e/redis/redis.key \
              --cert e2e/redis/redis.crt \
              -a 2aD6FgewLV
      - name: "Run Tests"
        run: |
          go test -v -timeout=30m -race -coverprofile=profile.cov ./...
      # Run Go benchmarks
      - name: Benchmark
        run: |
          go test -run=^$ -bench=. -benchmem ./...

  # Run the linter as a separate job
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24"]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2
          args: "--timeout=3m"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check Golang sources with Aligo
        uses: essentialkaos/aligo-action@v2
        with:
          files: ./...